### ISSUE TITLE
Need capability to mount volume as different uid/gid.

### ISSUE THREAD

**Issue by MattAtTTU** [vmware/vsphere-storage-for-docker#749]
The docker create command, when used with the default Docker volume driver, allows the user to specify uid and gid to control ownership of volume mount.  With this driver, that does not appear to be possible.  If one tries to supply the uid argument, the volume usage is displayed with driver options, which don't include uid.  

The documentation indicates use of uid should be possible since it says the docker create volume command is supported.  

Test:

`docker volume create --driver=vmdk --name=testvol -o uid=500 -o size=10gb -o diskformat=thin `

Result:

```
Error response from daemon: create testvol: VolumeDriver.Create: Invalid options: [u'uid'] 
Valid options and defaults: [('size', '100mb'), ('vsan-policy-name', '[VSAN default]'), ('diskformat', 'thin'), ('attach-as', 'independent_persistent'), ('access', 'read-write'), ('fstype', '')]
```

**Comment by msterin** [comment]
uid/gid This is a specific feature of the local volume driver, and it is not supported generically by Docker infra for volumes plugin, so we can't add it without a PR in Docker.

Details:
Docker VM gid/uid will not mean much on actual ESX storage where we keep the data. So we can enforce it only by persisting uid/gid in volume meta-data and enforcing on mount.  However when we are getting Mount from Docker, there is no info on uid/gid of the user requesting the operation, so we simply have no data to enforce anything. 

FWIW, I think in order to support uid/gid on external volumes ,Docker needs to pass uid/gid to all ops in Volume Driver API , so the driver can persist uid/gid passed on create, and use current gid/uid  during Mount to enforce.  //CC @cpuguy83

BTW - @MattAtTTU can you share a positive example (docker volume create with uid for local driver), just for reference ?

**Comment by cpuguy83** [comment]
Open to proposals on how we can support this at the engine API level.
Something like an on-mount-opt and support templating with container data (e.g. `{{ .User }}`)

**Comment by msterin** [comment]
FWIW I think all plugin ops need to have a context, and the uid/gid of the requesting user to be a part of the context. The plugin can take it from there. mount is just  a  case, create() may be equally important. 
Having it with container data does not really help as in plugin API I have no idea what container is requesting the volume

**Comment by brunotm** [comment]
Also options like uid/gid for mount usually exists only for filesystems that doesn't support unix permissions. So uid/guid setting for mount on filesystems like ext*, xfs and btrfs would have to be handled by the chown syscall on the host mount point.

I think that for persistent setting (on create) would suffice to handle both metadata at the vmdk_ops service and chown on plugin, but without context as @msterin mentioned or an update command and interface at the volume plugin level this would not be changeable by the user.

+1 for something like docker volume update volname -o opt=value

**Comment by govint** [comment]
As @msterin pointed out we need a good usecase where this would help or apply.

That apart the uid/gid can be tracked by the plugin to the FS can be mounted with the uid and gid options to mount  or the mount point itself is inside a dir that's owned by the uid/gid provided on create.  Thereby restricting access to the mount point to the uid/gid.
